name: Deploy TypeTypeType to GCP

env:
  SERVICE_NAME: typetypetyep


on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

  publish:
    needs: build
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker
        run: |
          docker build \
            -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest \
            -t game-server \
            -f Dockerfile.server .

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest


  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP VM
        run:
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${GCP_VM_IP} "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_TOKEN} && docker pull ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest"
